# towncrier.toml -*- mode: toml-mode -*-
# Summary:
#
# Tags:
#
## https://towncrier.readthedocs.io/en/stable/configuration.html
[tool.towncrier]
name                  = "bibble"
version               = "0.3.3"
directory             = "bibble/_docs/_changes"
filename              = "CHANGELOG.md"
template              = "bibble/_docs/_templates/news.md"
create_add_extension  = true
